# Generated by Django 5.1.7 on 2025-03-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lead_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='button',
        ),
    ]
