# Generated by Django 5.1.7 on 2025-04-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_lead_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='subject',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
