# Generated by Django 5.1.7 on 2025-04-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lead_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pagelink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
