# Generated by Django 5.1.7 on 2025-04-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lead_pagelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='pagelink',
        ),
        migrations.AddField(
            model_name='lead',
            name='page_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
