# Generated by Django 5.1.7 on 2025-04-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_lead_pagelink_lead_page_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('Unique Lead', 'Unique Lead'), ('Repeat Lead', 'Repeat Lead')], max_length=50, null=True),
        ),
    ]
