# Generated by Django 5.1.7 on 2025-04-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
