# Generated by Django 5.1.7 on 2025-04-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_lead_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='dealer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
